name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # ⚠️ 非常重要！确保可以拉取完整历史，避免 rebase 出错
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "tianshideyou@proton.me"
        git config --global user.name "tianshipapa"
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          git pull --rebase origin main  # ✅ 拉取远程最新版本并重放提交
          git push origin main
        else
          echo "No changes detected, skipping commit."
        fi
